// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIn3UdNmCp-KQOPeK10x2qpbqgMETmiwg',
    appId: '1:111417705184:web:a3a4d4abb2a572181b8685',
    messagingSenderId: '111417705184',
    projectId: 'sfs-utility',
    authDomain: 'sfs-utility.firebaseapp.com',
    storageBucket: 'sfs-utility.appspot.com',
    measurementId: 'G-J7GBSNE0FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkve7Y8L4ImEqqBgcwuWQjND2OW_jl55E',
    appId: '1:111417705184:android:4aab5a61fc7447db1b8685',
    messagingSenderId: '111417705184',
    projectId: 'sfs-utility',
    storageBucket: 'sfs-utility.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSeIesw6jeLUi_7hMawgdgiY9eVLSM7Ug',
    appId: '1:111417705184:ios:76b8135e7d4af90e1b8685',
    messagingSenderId: '111417705184',
    projectId: 'sfs-utility',
    storageBucket: 'sfs-utility.appspot.com',
    iosClientId: '111417705184-228nd7ju9eba1u8scjv13brttlb7g5hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolappfinal',
  );
}
